package com.bishwajeet.questionnaire.utils

const val QUESTION_KEY: String = "QUESTION_KEY"
const val USERNAME_KEY: String = "USERNAME_KEY"
const val POSITION_KEY: String = "POSITION_KEY"
const val ANSWER_KEY: String = "ANSWER_KEY"
const val CATEGORY_COUNTER_KEY: String = "CATEGORY_COUNTER_KEY"
const val QUESTION_COUNTER_KEY: String = "QUESTION_COUNTER_KEY"
const val CURRENT_QUESTION_KEY: String = "CURRENT_QUESTION_KEY"
const val LAST_QUESTION_KEY: String = "LAST_QUESTION_KEY"
const val SECOND_LAST_QUESTION_KEY: String = "SECOND_LAST_QUESTION_KEY"
const val INTENT_FROM_KEY = "FROM"
const val INTENT_SPLASH_VALUE = "SPLASH"
const val INTENT_READ_MODE = "INTENT_READ_MODE"
const val INTENT_WRITE_MODE = "INTENT_WRITE_MODE"
const val INTENT_READ_REQUEST_MODE = 9999
const val INTENT_WRITE_REQUEST_MODE = 8888
const val INTENT_OPERATION_MODE = "INTENT_OPERATION_MODE"
const val VAL_RETURN_NO_ANSWER = "No Answer Found"
const val RADIO_GROUP_ID = 13579